session: 'my'

min_participants_count: 5000 #от какого кол-ва подписчиков сохранять канналы

language_filter: other  # Опции: all, sng, other

names: #тут список ключевых слов
  - мото
  - авто
  - рыбалка
  - новости
  - киев


endings: #тут список окончаний
  - ''
  - 24
  - '4chan'